config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
      resources :collaborators, only: [:create, :destroy]
  end

  post 'add_collaborator/:id' => 'wikis#add_as_collaborator', as: "add_collaborator"
  get 'remove_collaborator/:id' => 'wikis#remove_as_collaborator', as: "remove_collaborator"

  resources :charges, only: [:new, :create]
  resources :wikis
  devise_for :users

  get "users/downgrade" => "users#downgrade"
  post "users/downgrade" => "users#downgrade"

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/amount.rb
class Amount < ActiveRecord::Base
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators
  has_many :wikis, through: :collaborators

  validates :role, inclusion: {in: %w(standard premium admin)}

  enum role: [:standard, :admin, :premium]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/charges_controller.rb
require 'amount'
# include Amount
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Upgrade to Premium Membership - #{current_user.email}",
      amount: 15_00
    }
  end

  def create
    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Upgrading to Premium Account - #{current_user.email}",
      currency: 'usd'
    )
    
    current_user.premium!
    flash[:notice] = "You have now successfully upgraded to the premium account!"
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  private

  def upgrade_account
      current_user.update_attribute(:role, 'premium')
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki_id

  def index
    @collaborators = @wiki.collaborators
    @users = User.all
  end

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = @wiki.collaborators.new(:user_id => params[:collaborator][:user_id])

    if @collaborator.save
       flash[:notice] = "Collaborator was added to this wiki."
       redirect_to @wiki
    else
       flash[:error] = "There was an error adding the collaborator.  Please try again."
       render :back
    end
  end

  def destroy
    @collaborator = @wiki.collaborators.find(params[:id])

    if @collaborator.destroy
       flash[:notice] = "Collaborator was removed from this wiki."
       redirect_to @wiki
    else
       flash[:error] = "Collaborator could not be removed. Please try again."
       render :index
    end
  end

  private

  def set_wiki_id
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def downgrade
    current_user.update(role: "standard")
    current_user.wikis.update_all(private: false)
    flash[:notice] = "You have been cancelled, #{current_user.email}."
    redirect_to edit_user_registration_path(current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborators
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.user = current_user
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki

    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again"
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated"
      redirect_to @wiki

    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again"
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path

    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end


  private
    def wiki_params
      params.require(:wiki).permit(:title, :body, :public)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    @text = text
    renderer = Redcarpet::Render::HTML.new
    extensions = {
      tables: true,
      autolink: true,
      hard_wrap: true,
      strikethrough: true,
      fenced_code_blocks: true,
      quote: true,
      highlight: true,
      underline: true,
      footnotes: true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/index.html.erb
<h1>Charges#index</h1>
<p>Find me in app/views/charges/index.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Subscribe to Blocipedia Premium.</h4>
   <p>The cost of a premium upgrade is $15. Click below to upgrade.</p>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%=
   @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%=
   @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_form.html.erb
<div class= 'form-group'>
  <h3>Collaborators</h3>
    <% if @wiki.user == current_user %>
      <%= form_tag(collaborators_path, action: :create, method: :post) do%>
        <%= hidden_field_tag :wiki_id, @wiki.id %>
        Enter email of the collaborator: <%= text_field_tag :email %>
        <%= submit_tag 'Add collaborator' %>
      <% end %>
    <% end %>

    <% @wiki.collaborators.each do |user| %>
      <div>
        <%= user.user.email %>
        <% if @wiki.user == current_user %>
          <%= link_to "Remove collaborator", user, method: :delete, data: {confirm: 'Are you sure you want remove user as a collaborator?'} %>
        <% end %>
    </div>
    <% end %>
</div>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
     <div class="pull-right user-info">
       <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
       <% end %>
     </div>
    </ul>
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Wiki, Wiki, What!</h1>
  <p>A wikipedia clone</p>
  <p>
    <% unless user_signed_in? %>
         <h5>Create and share Wikis</h5>
         <%= link_to "Sign In!", new_user_session_path, class: "btn btn-primary" %>
       <% else %>
         <h5>Create and share Wikis</h5>
         <p>Logged in with <span><%= current_user.email %></span>!</p>
         <%= link_to "Wikis", wikis_path, class: "btn btn-primary" %>
       <% end %>
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Wiki, Wiki, What! will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Wiki, Wiki, What! will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Wiki, Wiki, What! will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for Wikis</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>

    <div class="col-md-8">
        <%= form_for @wiki do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
            </div>

            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
            </div>


            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
    <div class="form-group">
        <% if current_user.admin? || current_user.premium? %>
          <h4>Add Collaborators</h4>
          <%= form_for [@wiki, Collaborator.new] do |c| %>
          <%= c.collection_select :user_id, User.all, :id, :email, prompt: true %>
            <%= c.submit "Add collaborator", class: 'btn btn-primary' %>
          <% end %>
        <% end %>
    </div>
    <h4>Collaborators</h4>
        <% @wiki.collaborators.each do |collaborator| %>
          <p>
            <%= collaborator.user.email %>
            <%= link_to "Remove", wiki_collaborator_path(@wiki, collaborator), :method => :delete %>
          </p>
          <% end %>
    <br>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div class="new-wiki">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for Wikis</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>

    <div class="col-md-8">
        <%= form_for @wiki do |f| %>

        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>

        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>

        <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
                <%= f.check_box :private %> Private Topic
            <% end %>
        </div>

        <div class="form-group">
          <%= f.label :collaborators %>
          <%= f.text_field :collaborators, class: 'form-control', placeholder: "Enter collaborator email" %>
          <%= f.submit "Add", class: 'btn btn-success' %> <%= f.submit "Remove", class: 'btn btn-danger' %>
        </div>

        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>

        <% end %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
    <div class="col-md-8">
        <p><%= link_to markdown(@wiki.body).html_safe %></p>
        <h4> Private? <%= @wiki.private %></h4>
        <h4> Collaborators: <% if current_user.admin? || current_user.id == @wiki.user_id? %>
          <% @wiki.collaborators.each do |collaborator| %>
              <%= collaborator.user.email %>
            <% end %>
          <% end %>
      </h4>
    </div>


    <div class="col-md-4">
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' if policy(@wiki).update? %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} if policy(@wiki).destroy? %>
    </div>
</div>